### ISSUE TITLE
The load speed of the website is slow.

### ISSUE THREAD

**Issue by PeterDaveHello** [buildbot/buildbot-website#21]
Does anyone have the same problem as me?
It'll always take few more seconds to load the pages then other websites. :dizzy_face:

**Comment by PeterDaveHello** [comment]
The size of whole contents on mainpage is 1.2MB, maybe is too large.

**Comment by djmitche** [comment]
It loads pretty fast for me, but I don't have an issue with optimizing

**Comment by tardyp** [comment]
changing the page to purely static probably made it much faster. total size if now 478kb with images
