### ISSUE TITLE
Valid syntax in Quick Tour Configuration Errors Section

### ISSUE THREAD

**Issue by hackerkid** [buildbot/buildbot-website#23]
In the configuration errors section ([quick tour](http://docs.buildbot.net/current/tutorial/tour.html#quick-tour-label)) the reader is asked to introduce an error by removing the first single quote in the two lines they just changed. 

The result should be 
```python
c[title'] = "Pyflakes"
c[titleURL'] = "http://divmod.org/trac/wiki/DivmodPyflakes"
```
But the tour shows the syntax without any errors.  
```python
c['title'] = "Pyflakes"
c['titleURL'] = "http://divmod.org/trac/wiki/DivmodPyflakes"
```

**Comment by djmitche** [comment]
Thanks!  This was fixed in https://github.com/buildbot/buildbot/commit/fba065a92ef5ed2c567cb5729102d1a5c9bbb3ed and is visible in the "latest" docs -- "current" is from the previous release.
