### ISSUE TITLE
wrong example on devel documentation, first run

### ISSUE THREAD

**Issue by MalloZup** [buildbot/buildbot-website#24]
on the page : http://docs.buildbot.net/latest/tutorial/firstrun.html#getting-ready

when setting up the worker:
```
/bin/buildslave create-slave worker localhost example-worker pass
```
but the master has the following configuration : 
```
c['slaves'] = [buildslave.BuildSlave("example-slave", "pass")]
```
Thx to the issue i learned quickly buildbot, but should be suggested the same. :)

**Comment by djmitche** [comment]
Thanks -- this is a symptom of using the "latest" documentation with the "current" version -- if you look replace `/latest/` with `/current/` in the URL, you'll see the version corresponding to the buildbot you're running.

**Comment by MalloZup** [comment]
ok got it. thx. :) i really like buildbot :)
