### ISSUE TITLE
Issues for the main buildbot project

### ISSUE THREAD

**Issue by MeLight** [buildbot/buildbot-website#25]
There's no option for leaving issues on the main project, and no contact on the website. So forgive me if it's misplaced, just didnt find the right channel.

 I wasn't able to complete the tutorial on two separate, fresh GCE instances running Ubuntu 16.4
This the log (`tail -n 20 master/twistd.log`):

```
_inlineCallbacks(r, g, deferred)
          File "/home/yuri/tmp/buildbot/sandbox/local/lib/python2.7/site-packages/Twisted-16.2.0-py2.7-linux-x86
_64.egg/twisted/internet/defer.py", line 1128, in _inlineCallbacks
            result = g.send(result)
          File "/home/yuri/tmp/buildbot/sandbox/local/lib/python2.7/site-packages/buildbot-0.9.0rc1-py2.7.egg/bu
ildbot/util/service.py", line 45, in reconfigServiceWithBuildbotConfig
            yield svc.reconfigServiceWithBuildbotConfig(new_config)
          File "/home/yuri/tmp/buildbot/sandbox/local/lib/python2.7/site-packages/Twisted-16.2.0-py2.7-linux-x86
_64.egg/twisted/internet/defer.py", line 1274, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/home/yuri/tmp/buildbot/sandbox/local/lib/python2.7/site-packages/Twisted-16.2.0-py2.7-linux-x86
_64.egg/twisted/internet/defer.py", line 1128, in _inlineCallbacks
            result = g.send(result)
          File "/home/yuri/tmp/buildbot/sandbox/local/lib/python2.7/site-packages/buildbot-0.9.0rc1-py2.7.egg/bu
ildbot/www/service.py", line 81, in reconfigServiceWithBuildbotConfig
            self.setupSite(new_config)
          File "/home/yuri/tmp/buildbot/sandbox/local/lib/python2.7/site-packages/buildbot-0.9.0rc1-py2.7.egg/bu
ildbot/www/service.py", line 138, in setupSite
            raise RuntimeError("could not find buildbot-www; is it installed?")
        exceptions.RuntimeError: could not find buildbot-www; is it installed?

```

**Comment by djmitche** [comment]
The `pip install buildbot[bundle]` step should have installed buildbot-www for you.  It seems it did not.  Did you run that step correctly?

"No contact on the website"?  Except the menu item labeled "[contact](http://buildbot.net/contact.html)" perhaps?

**Comment by MeLight** [comment]
Yeap, ran it twice to make sure I'm not missing anything.

**Comment by djmitche** [comment]
Does it not install buildbot-www?

**Comment by MeLight** [comment]
Attempt number four:
```
The buildmaster startup failed. Please see 'twistd.log' for possible reason.
(sandbox) yuri@buildbot:~/tmp/buildbot$ tail -n 20 master/twistd.log 
            _inlineCallbacks(r, g, deferred)
          File "/home/yuri/tmp/buildbot/sandbox/local/lib/python2.7/site-packages/Twisted-16.2.0-py2.7-linux-x86
_64.egg/twisted/internet/defer.py", line 1128, in _inlineCallbacks
            result = g.send(result)
          File "/home/yuri/tmp/buildbot/sandbox/local/lib/python2.7/site-packages/buildbot-0.9.0rc1-py2.7.egg/bu
ildbot/util/service.py", line 45, in reconfigServiceWithBuildbotConfig
            yield svc.reconfigServiceWithBuildbotConfig(new_config)
          File "/home/yuri/tmp/buildbot/sandbox/local/lib/python2.7/site-packages/Twisted-16.2.0-py2.7-linux-x86
_64.egg/twisted/internet/defer.py", line 1274, in unwindGenerator
            return _inlineCallbacks(None, gen, Deferred())
        --- <exception caught here> ---
          File "/home/yuri/tmp/buildbot/sandbox/local/lib/python2.7/site-packages/Twisted-16.2.0-py2.7-linux-x86
_64.egg/twisted/internet/defer.py", line 1128, in _inlineCallbacks
            result = g.send(result)
          File "/home/yuri/tmp/buildbot/sandbox/local/lib/python2.7/site-packages/buildbot-0.9.0rc1-py2.7.egg/bu
ildbot/www/service.py", line 81, in reconfigServiceWithBuildbotConfig
            self.setupSite(new_config)
          File "/home/yuri/tmp/buildbot/sandbox/local/lib/python2.7/site-packages/buildbot-0.9.0rc1-py2.7.egg/bu
ildbot/www/service.py", line 138, in setupSite
            raise RuntimeError("could not find buildbot-www; is it installed?")
        exceptions.RuntimeError: could not find buildbot-www; is it installed?
2016-07-18 11:40:24+0000 [-] BuildMaster startup failed
2016-07-18 11:40:24+0000 [-] BuildMaster is stopped
2016-07-18 11:40:24+0000 [-] Main loop terminated.
2016-07-18 11:40:24+0000 [-] Server Shut Down.
(sandbox) yuri@buildbot:~/tmp/buildbot$ sudo apt-get install buildbot-www
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package buildbot-www
(sandbox) yuri@buildbot:~/tmp/buildbot$ 
```

Getting the sensation that I'm missing something.

As a side note, I tried to open this issue on trac.buildbot.net, but was rejected as potential spammer. So, we'll continue discussing it here :cry:

**Comment by sa2ajj** [comment]
@MeLight: just to make sure -- you only see these problems during the start of Buildbot master?

**Comment by MeLight** [comment]
@sa2ajj hi, yes. Trying to follow the tutorial here: http://docs.buildbot.net/current/tutorial/firstrun.html

Can't get past the `builbot create-master` step.

**Comment by djmitche** [comment]
Ah, so two things are wrong here.  First, the "current" documentation refers to 0.8.12, but you're installing 0.9.0rc1.  I suspect that may be a pip error, as it should not yet be installing the release candidate.

The second thing is, you're running `sudo apt-get install buildbot-www` which is not at all the same as `pip install buildbot[bundle]`.

To work around the pip issue, try `pip install buildbot[bundle]==0.8.12`

**Comment by MeLight** [comment]
Forgot to mention, I did `pip install buildbot[bundle]` - same result. Also did `pip install buildbot[bundle]==0.8.12`, got this:
```
OSError: [Errno 2] No such file or directory: '/home/yuri/tmp/buildbot/sandbox/local/lib/python2.7/site-packages
/SQLAlchemy-1.1.0b2-py2.7-linux-x86_64.egg'
```

Also, the `pip install buildbot[bundle]==0.8.12` does not appear anywhere in the tutorial. If I want to start over, which commands sequence should I run in order to test drive the product?

My OS of choice is Ubuntu, but I'm using GCE machines, so dont mind trying another (recommended?) OS.

Please advise

**Comment by djmitche** [comment]
That "no such file or directory" error is a weird one.  

The thing that's making this confusing is that we're just about to release 0.9.0, and
  http://docs.buildbot.net/latest/tutorial/firstrun.html
is the tutorial for that version; conversely
  http://docs.buildbot.net/current/tutorial/firstrun.html
documents 0.8.12, the most recent stable release.  I believe the "easy_install" command there is not smart enough to realize that the 0.9.0rc1 version on pypi is a release candidate and thus shouldn't be installed.

You will want to avoid installing Buildbot at all using apt-get, as that is generally a different version than what you install with pip, and they don't get along well.  It might be best to start with a clean image?  It's probably best for you to run the tutorial with the new version, in which case follow the instructions on the first link (http://docs.buildbot.net/latest/tutorial/firstrun.html), but add `--pre` to the pip command:

    ./bin/pip install --pre buildbot[bundle]

which will instruct it to install the release candidate.

Sorry that you hit things just at the moment when the old commands stopped working (because there's a release candidate out now), but the new commands don't work yet (because the release hasn't occurred yet)

**Comment by tardyp** [comment]
File or fix a bug link is on the main web site
