### ISSUE TITLE
index.html misses Analytics tracking code

### ISSUE THREAD

**Issue by rutsky** [buildbot/buildbot-website#36]
Looks like introduced in d3170eb9e, was included here: https://github.com/buildbot/buildbot-website/commit/d3170eb9e9d7ae2cb684d30b33cd667bbbdad2b4#diff-ad05cd303819776407ed64e6f9367d91L17

**Comment by tardyp** [comment]
its not like we are actually looking at those analytics. most of our users probably have add blockers. So lets say its a volonteer drop for user's privacy XD
