### ISSUE TITLE
buildbot-website updates are not happening

### ISSUE THREAD

**Issue by rodrigc** [buildbot/buildbot-website#47]
https://github.com/buildbot/buildbot-website/pull/46 was merged, but the https://buildbot.net website was not updated

**Comment by djmitche** [comment]
@tardyp, @seankelly looked into this a bit in the meeting, but wasn't able to see why Harp was missing.

**Comment by seankelly** [comment]
```
gmake: Entering directory '/usr/home/bbuser/site/node_modules/node-sass/build'
  c++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-DBUILDING_NODE_EXTENSION' -I/home/bbuser/.node-gyp/10.12.0/include/node -I/home/bbuser/.node-gyp/10.12.0/src -I/home/bbuser/.node-gyp/10.12.0/deps/uv/include -I/home/bbuser/.node-gyp/10.12.0/deps/v8/include -I../../nan  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -D_LIBCPP_TRIVIAL_PAIR_COPY_CTOR=1 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++1y -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
...
In file included from ../src/binding.cpp:3:
../src/sass_context_wrapper.h:8:10: fatal error: 'sass/context.h' file not found
#include <sass/context.h>
```
```
$ pkg query %Fp libsass | grep context
/usr/local/include/sass/context.h
```
I think the compile is missing `-I /usr/local/include` because it's a FreeBSD host so packages are in `/usr/local` instead of `/usr`.

**Comment by seankelly** [comment]
We might need to update dependencies. The jail is using Node 10.12. Node-sass says 4.9 is the minimum version for Node 10.x. Besides the error above, there are a lot of deprecation warnings.

**Comment by kwk** [comment]
What's the status of this? I see that this discussion is close to a year old and I think it would be very good for new users if they can get to the correct "dog-fooding URL". I'm new here so sorry if my words sound too harsh. No offense-

**Comment by tardyp** [comment]
forgot about this. turned out we used npm instead of yarn, and wouldn't use the dep freezing features.

**Comment by p12tic** [comment]
I believe this bug is no longer happening.
