### ISSUE TITLE
Typo in docs

### ISSUE THREAD

**Issue by ryandesign** [buildbot/buildbot-website#48]
This bug report is for http://docs.buildbot.net/current/manual/configuration/www.html. I couldn't figure out if there was a different place I was supposed to report this issue.

This:

> for each or the organizations

should be changed to this:

> for each **of** the organizations

**Comment by ryandesign** [comment]
And at http://docs.buildbot.net/current/manual/upgrading/0.9-upgrade.html#web-status there is a stray closing backtick here:

> replaced with configuration in c['www']`.

**Comment by ryandesign** [comment]
At http://docs.buildbot.net/current/manual/configuration/www.html#endpoint-matchers

> This endpoint matcher is matches current and future control endpoints

should be

> This endpoint matcher matches current and future control endpoints

**Comment by ryandesign** [comment]
At http://docs.buildbot.net/latest/developer/quickstart.html

> make is easy to dive into the code

should be

> make **it** easy to dive into the code

**Comment by tardyp** [comment]
I think the easiest is for you to just fix those typo in the code as you find them. It would be much apreciated!

just grep for the sentence in *.rst files in the main repository

**Comment by tardyp** [comment]
e.g: https://github.com/buildbot/buildbot/blob/f0b3f1ef84bb6559f800d4f0001ef2cc35bd002f/master/docs/developer/quickstart.rst#L1
