### ISSUE TITLE
Remove link to Google+

### ISSUE THREAD

**Issue by cwfoo** [buildbot/buildbot-website#58]
https://github.com/buildbot/buildbot-website/blob/ab660203408dc392e26776664826a2fbb103add0/src/_include/layout.jade#L41

Google+ was discontinued in 2019.

**Comment by tardyp** [comment]
done thanks for heads up

**Comment by cwfoo** [comment]
Fixed in a353180aa3d9f46b4ed358ae34aca4ae3615c467
