### ISSUE TITLE
Horrible javascript scrolling ignoring accessibility settings

### ISSUE THREAD

**Issue by Arteneko** [buildbot/buildbot-website#67]
The current website has a horrendously aggressive "smooth" scrolling that completely ignores motion reduction / suppression settings.

The website should respect said settings and not throw a sickening scroll effect when the user clearly states that such effect makes them sick (ie `prefers-reduced-motion` media query).

**Comment by tardyp** [comment]
Hello,
Sorry, this website was designed at a time where prefers-reduced-motion (chrome 79 => 2019) was not a thing and were smooth scrolling was a very cool thing.
It is not anymore and we should probably get totally rid of that.

We will fix that.

**Comment by tardyp** [comment]
fixed via 8440ddb80eb20fa1e5169f1814370b60dd274ded
