### ISSUE TITLE
Remove mailing list links

### ISSUE THREAD

**Issue by ari** [buildbot/buildbot-website#68]
The maiing list has been dead quite a while now. Remove it from the website to avoid leading people into the impression that buildbot is dead.

I'd have submitted a pull request, but I can't figure out where the site content is.

**Comment by tardyp** [comment]
Well, the mailing list is indeed low activity, but we try to answer it when we can. If people prefer emails, I don't see why we should spend time closing it.

**Comment by ari** [comment]
The TLS certificate expired earlier this year and the archiving mechanism is broken. So I reckon no one is likely to subscribe. I personally like email communication, but a searchable mailing list is pretty important if it is to be used as a resource.

Even longer ago there was another mailing list I found here: https://markmail.org/search/?q=list%3Anet.sourceforge.lists.buildbot-devel

**Comment by tardyp** [comment]
ah indeed, this is an issue on our lets encrypt setup. 
This is fixed now, thanks for reporting!

**Comment by ari** [comment]
Great, but I don't think it is quite fixed yet.

https://lists.buildbot.net/pipermail/users/

That's missing all emails since May.
