### ISSUE TITLE
No download link available

### ISSUE THREAD

**Issue by benallard** [buildbot/buildbot-website#8]
Most of the time, If I go to buildbot.net, I want to download the latest packages.

I did not found a download link.

**Comment by sa2ajj** [comment]
There's a `Download and Install` item in `Get Started` menu.

Would you like something else?

**Comment by benallard** [comment]
I was more thinking about a direct link to the latest tar ball.

**Comment by djmitche** [comment]
Since it's a Python package, clicking a link in your browser is not the most common means of downloading the app.  I think that the "Download and Install" link does a good job of summarizing the options -- better than linking to a tarball or even the pypi page.

**Comment by benallard** [comment]
What about explicitly showing "pip install build{bot,slave}" (probably in two lines), then ? When I land on such a page, there are two things I want to know: "Why is it for me ?", "How to install it ?". I believe the former is addressed, the later needs too much action (investigate the menus + 2 clicks).

**Comment by djmitche** [comment]
I'm not opposed, I'm just not sure where it would fit.  Want to send a pull req with your idea? (hint: https://github.com/djmitche/git-issue2pr)

**Comment by tardyp** [comment]
I think the Discover Builder | Get Started | Get Involved menus are addressing what you say.

With the fact that buildbot is a framework and not an application, I guess it would be misleading to let people install it without going through the tutorial first.
